site_name: Biodiversity bioinformatics
nav:
    - Home: index.md
    - Precourse preparations and Gitpod information: precourse.md
    - Course schedule: course_schedule.md
    - Day 1 - Introduction to molecular evolution & phylogenetics:
      - General information and course material: course_material/day1/1_general.md
      - Links to the OMA Academy modules: course_material/day1/2_exercices.md
    - Day 2 - Orthology-focused arthropod comparative genomics:
      - General information and course material: course_material/day2/1_general.md
      - Software and resources: course_material/day2/2_software.md
      - BUSCO - the what, why, and how!: course_material/day2/3_busco.md
      - Homology, Orthology, & Paralogy: course_material/day2/4_homology.md
      - Gene-Tree-Species-Tree Reconciliation: course_material/day2/5_reconciliation.md
      - Gene Family Ancestral State Reconstruction: course_material/day2/6_reconstruction.md
    - Day 3 - Duplication of genes and genomes, expression:
      - General information and course material: course_material/day3/1_general.md
      - Software and R packages: course_material/day3/2_software.md
      - Finding information on gene function at small scale: course_material/day3/3_gene_function.md
      - Finding information about function of a group of genes: course_material/day3/4_group_function.md
      - Function of duplicated genes: course_material/day3/5_duplicated_function.md

theme:
  name: material
  logo: assets/images/general/SIB_logo.svg
  favicon: assets/images/general/SIB_logo.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.code.copy

extra:
  version:
    provider: mike

copyright:
  Copyright &copy; 2021-2025 SIB Swiss institute of Bioinformatics -
  <a href="#__consent">Change cookie settings</a>

# Repository
repo_name: sib-swiss/biodiversity-bioinformatics
repo_url: https://github.com/sib-swiss/biodiversity-bioinformatics
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css
